package main

import (
	"testing"
	"net/http"
	"fmt"
	"io/ioutil"
	"encoding/json"
)

func TestTest(t *testing.T) {
	myPrint("test")
}

func TestTestTest(t *testing.T) {
/*
	type Reservation struct {
		id     int
		CID    int
		ITEMID int
	}*/

	type AutoGenerated struct {
		Data struct {
			Reservations []struct {
				CID    int `json:"cId"`
				ID     int `json:"id"`
				ItemID int `json:"itemId"`
			} `json:"reservations"`
		} `json:"data"`
	}

	var client http.Client
	resp, err := client.Get("https://ppl-reservation-beta.herokuapp.com/reservations?query={reservations(cId:1){id,cId,itemId}}")
	if err != nil {
		// err
	}
	defer resp.Body.Close()
	bodyBytes, _ := ioutil.ReadAll(resp.Body)

	data := AutoGenerated{}
	json.Unmarshal(bodyBytes, &data)

	for i:=0; i< len(data.Data.Reservations); i++ {
		fmt.Printf("ID: %d ",data.Data.Reservations[i].ID)
		fmt.Printf("cId: %d ",data.Data.Reservations[i].CID)
		fmt.Printf("ItemId: %d ",data.Data.Reservations[i].ItemID)
		print("\n")
	}

}
